"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type PortalLanguage = "en" | "vi";

type PortalLanguageContextValue = {
  language: PortalLanguage;
  setLanguage: (language: PortalLanguage) => void;
  t: (key: string, fallback?: string) => string;
};

const PORTAL_LANGUAGE_STORAGE_KEY = "cozorohome-portal-language";

const translations: Record<string, { en: string; vi: string }> = {
  portalTitle: { en: "CozoroHome Portal", vi: "Cổng thông tin CozoroHome" },
  home: { en: "Home", vi: "Trang chủ" },
  clientServices: { en: "Cozoronian Services", vi: "Dịch vụ Khách hàng" },
  billingCenter: { en: "Billing & Fines", vi: "Thanh toán và tiền phạt" },
  bookings: { en: "Bookings", vi: "Đặt lịch" },
  controller: { en: "Controller", vi: "Điều khiển" },
  accountOverview: { en: "Account Overview", vi: "Tổng quan tài khoản" },
  coins: { en: "Coins", vi: "Cozoro Coins" },
  payments: { en: "Payments", vi: "Thanh toán" },
  fines: { en: "Fines", vi: "Tiền phạt" },
  cleaningSchedule: { en: "Cleaning Schedule", vi: "Lịch vệ sinh" },
  adminCleaning: { en: "Admin Cleaning", vi: "Phân công lịch vệ sinh" },
  manager: { en: "Manager", vi: "Quản lý" },
  notifications: { en: "Notifications", vi: "Thông báo" },
  support: { en: "Messages", vi: "Tin nhắn" },
  clientLogin: { en: "Cozoronian Login", vi: "Đăng nhập Khách hàng" },
  language: { en: "Language", vi: "Ngôn ngữ" },
  english: { en: "English", vi: "Tiếng Anh" },
  vietnamese: { en: "Vietnamese", vi: "Tiếng Việt" },
  homepageTitle: { en: "CozoroHome Portal", vi: "Cổng thông tin CozoroHome" },
  paymentHistory: { en: "Payment History", vi: "Lịch sử thanh toán" },
  viewPaymentHistory: { en: "View payment history", vi: "Xem lịch sử thanh toán" },
  refreshPayments: { en: "Refresh payments", vi: "Làm mới thanh toán" },
  myPaymentEntries: { en: "My Payment Entries", vi: "Các khoản thanh toán của tôi" },
  purpose: { en: "Purpose", vi: "Mục đích" },
  sort: { en: "Sort", vi: "Sắp xếp" },
  nextPayment: { en: "Next Payment", vi: "Kỳ thanh toán tiếp theo" },
  coinsTitle: { en: "Coins", vi: "Cozoro Coins" },
  viewCoinHistory: { en: "View coin history", vi: "Xem lịch sử coin" },
  refreshCoins: { en: "Refresh coins", vi: "Làm mới coin" },
  myCoinEntries: { en: "My Coin Entries", vi: "Giao dịch coin của tôi" },
  recentHistory: { en: "Recent history", vi: "Lịch sử gần đây" },
  showFilters: { en: "Show filters and more history", vi: "Hiện bộ lọc và thêm lịch sử" },
  hideFilters: { en: "Hide filters and full history", vi: "Ẩn bộ lọc và toàn bộ lịch sử" },
  showMore10: { en: "Show 10 more", vi: "Xem thêm 10 dòng" },
  showFewer: { en: "Show fewer", vi: "Thu gọn" },
  event: { en: "Event", vi: "Sự kiện" },
  timestamp: { en: "Timestamp", vi: "Thời gian" },
  operator: { en: "Operator", vi: "Người thao tác" },
  finesTitle: { en: "Fines", vi: "Tiền phạt" },
  viewFineHistory: { en: "View fine history", vi: "Xem lịch sử tiền phạt" },
  refreshFines: { en: "Refresh fines", vi: "Làm mới tiền phạt" },
  laundryBookingsTitle: { en: "Laundry Bookings", vi: "Đặt lịch giặt sấy" },
  acControllerTitle: { en: "Room Controller", vi: "Điều khiển máy lạnh" },
  loadBookingOptions: { en: "Load booking options", vi: "Tải tùy chọn đặt lịch" },
  bookLaundrySlot: { en: "Book laundry slot", vi: "Đặt lịch giặt sấy" },
  accountOverviewTitle: { en: "Account Overview", vi: "Tổng quan tài khoản" },
  service: { en: "Service", vi: "Dịch vụ" },
  schedule: { en: "Schedule", vi: "Lịch trình" },
  userView: { en: "User view", vi: "Giao diện người dùng" },
  managerView: { en: "Manager view", vi: "Giao diện quản lý" },
  signedInAs: { en: "Signed in as", vi: "Đăng nhập với" },
  logout: { en: "Log out", vi: "Đăng xuất" },
  loginRequired: { en: "Login Required", vi: "Yêu cầu đăng nhập" },
  loginRequiredSub: { en: "Please sign in with an active Cozoronian email or a pre-approved Cozoro team email before using the portal.", vi: "Vui lòng đăng nhập bằng email Khách hàng đang hoạt động hoặc email được nhóm Cozoro phê duyệt trước khi sử dụng cổng thông tin." },
  goToLogin: { en: "Go to login", vi: "Đi đến trang đăng nhập" },
  laundryQuickLink: { en: "Laundry", vi: "Giặt sấy" },
  laundryDesc: { en: "Book laundry and check machine availability", vi: "Đặt lịch giặt sấy và kiểm tra tình trạng máy" },
  controllerDesc: { en: "Control your room devices", vi: "Điều khiển thiết bị trong phòng của bạn" },
  scheduleDesc: { en: "See cleaning duties and next laundry", vi: "Xem lịch trực vệ sinh và lịch giặt sấy tiếp theo" },
  billingsDesc: { en: "Review laundry fees and fines", vi: "Xem phí giặt sấy và tiền phạt" },
  coinsDesc: { en: "Check your current coins and Cozoronian status", vi: "Xem số lượng coin hiện tại và trạng thái Khách hàng" },
  finesDesc: { en: "Review unpaid fine tickets", vi: "Xem các phiếu phạt chưa thanh toán" },
  yourDashboard: { en: "Your dashboard", vi: "Bảng điều khiển của bạn" },
  dashboardSubtext: { en: "A quick view of your account, bookings, cleaning schedule, and unpaid fine tickets.", vi: "Xem nhanh tài khoản, lịch giặt sấy, lịch trực vệ sinh và các phiếu phạt chưa thanh toán." },
  refreshing: { en: "Refreshing...", vi: "Đang làm mới..." },
  refreshDashboard: { en: "Refresh dashboard", vi: "Làm mới bảng điều khiển" },
  signInToView: { en: "Sign in first to view your dashboard.", vi: "Đăng nhập trước để xem bảng điều khiển của bạn." },
  unableToLoadDashboard: { en: "Unable to load dashboard.", vi: "Không thể tải bảng điều khiển." },
  dashboardPartialData: { en: "Dashboard loaded with partial data.", vi: "Bảng điều khiển được tải với dữ liệu không đầy đủ." },
  unableToLoadRightNow: { en: "Unable to load dashboard right now.", vi: "Hiện tại không thể tải bảng điều khiển." },
  currentCoins: { en: "Current Coins", vi: "Số coin hiện tại" },
  coinsEarnedLastMonth: { en: "Coins Earned Last Month", vi: "Số coin kiếm được tháng trước" },
  coinsEarnedThisMonth: { en: "Coins Earned This Month", vi: "Số coin kiếm được tháng này" },
  nextCleaning: { en: "Next Cleaning", vi: "Lịch vệ sinh tiếp theo" },
  unpaidFineTickets: { en: "Unpaid Fine Tickets", vi: "Phiếu phạt chưa thanh toán" },
  noUpcomingTask: { en: "No upcoming task", vi: "Không có lịch sắp tới" },
  clearForNow: { en: "You are clear for now.", vi: "Hiện tại bạn chưa có lịch." },
  totalUnpaidAmount: { en: "Total unpaid amount", vi: "Tổng tiền chưa nộp" },
  briefUserInfo: { en: "Brief Cozoronian Info", vi: "Thông tin cơ bản Khách hàng" },
  openFullAccount: { en: "Open full account", vi: "Mở tài khoản" },
  name: { en: "Name", vi: "Tên" },
  branch: { en: "Branch", vi: "Chi nhánh" },
  bedNumber: { en: "Bed Number", vi: "Giường" },
  floorLabel: { en: "Floor", vi: "Tầng" },
  roomLabel: { en: "Room", vi: "Phòng" },
  phone: { en: "Phone", vi: "Số điện thoại" },
  emailLabel: { en: "Email", vi: "Email" },
  nextLaundry: { en: "Next Laundry", vi: "Lịch giặt sấy tới" },
  openLaundry: { en: "Open laundry", vi: "Mở giặt sấy" },
  noUpcomingLaundry: { en: "No upcoming laundry booking is scheduled.", vi: "Chưa có lịch đặt máy tiếp theo." },
  status: { en: "Status", vi: "Trạng thái" },
  accountSnapshot: { en: "Account Snapshot", vi: "Tóm tắt tài khoản" },
  reviewFines: { en: "Review fines", vi: "Xem tiền phạt" },
  cozoroMember: { en: "Cozoro Member", vi: "Thành viên Cozoro" },
  contractCode: { en: "Contract Code", vi: "Mã HD" },
  paidThrough: { en: "Paid Through", vi: "Đã thanh toán đến" },
  coinsUsedByMonth: { en: "Coins Used by Month", vi: "Coin sử dụng theo tháng" },
  openCoins: { en: "Open coins", vi: "Mở trang coin" },
  noMonthlyCoinUsage: { en: "No monthly coin usage is available yet.", vi: "Chưa có thay đổi coin nào theo tháng." },
  coinsUsedByCategory: { en: "Coins Used by Category", vi: "Coin sử dụng theo Danh mục" },
  noCategoryCoinUsage: { en: "No coin usage categories are available yet.", vi: "Chưa có thay đổi coin nào theo danh mục." },
  enterPasswordClient: { en: "Enter your password. For Cozoronians, the default first password is your phone number.", vi: "Nhập mật khẩu. Với Khách hàng, mật khẩu mặc định là số điện thoại." },
  onlyActiveUsersLogin: { en: "Only active users or pre-approved Cozoro team emails can log in.", vi: "Chỉ người dùng đang hoạt động hoặc email được phê duyệt mới được đăng nhập." },
  changePasswordToContinue: { en: "Please change your password before continuing.", vi: "Vui lòng đổi mật khẩu trước khi tiếp tục." },
  defaultPasswordAccepted: { en: "Default password accepted. Cozoronian information loaded.", vi: "Đã chấp nhận mật khẩu mặc định. Đã tải thông tin Khách hàng." },
  passwordCreatedSuffix: { en: "Password created.", vi: "Đã tạo mật khẩu." },
  viewLoadedSuffix: { en: "view loaded.", vi: "đã được tải." },
  clientInfoLoaded: { en: "Cozoronian information loaded.", vi: "Đã tải thông tin Khách hàng." },
  apiRequestFailed: { en: "API request failed. Make sure the API is running and Google Sheets has been connected.", vi: "Yêu cầu API thất bại. Đảm bảo API đang chạy và kết nối Sheets." },
  googleSignInSuccessClient: { en: "Google sign-in successful. Cozoronian information loaded.", vi: "Đăng nhập Google thành công. Đã tải thông tin Khách hàng." },
  googleSignInSuccess: { en: "Google sign-in successful.", vi: "Đăng nhập Google thành công." },
  googleSignInFailed: { en: "Google sign-in failed.", vi: "Đăng nhập Google thất bại." },
  portalSession: { en: "Portal Session", vi: "Phiên người dùng" },
  clientLoginHeader: { en: "Cozoronian Login", vi: "Đăng nhập Khách hàng" },
  activeUsersCanLogin: { en: "Active Cozoronians can log in from the list. Cozoro team members can also log in if an owner has pre-approved their email.", vi: "Khách hàng có thể đăng nhập. Thành viên Cozoro cũng có thể đăng nhập nếu đã được phê duyệt email." },
  useGoogleToSignIn: { en: "Use Google to sign in with the account tied to your active Cozoronian or approved app management email.", vi: "Dùng Google đăng nhập với tài khoản liên kết hoặc email được phê duyệt." },
  passwordToolsBelow: { en: "Password tools are in the Account Security section below.", vi: "Các công cụ mật khẩu nằm trong mục Bảo mật Tài khoản bên dưới." },
  changePassword: { en: "Change password", vi: "Đổi mật khẩu" },
  useAnotherEmail: { en: "Use another email", vi: "Dùng email khác" },
  continueWithGoogle: { en: "Continue with Google", vi: "Tiếp tục với Google" },
  signInGoogleTied: { en: "Sign in with the Google account tied to your active Cozoronian or approved Cozoro team email.", vi: "Đăng nhập bằng tài khoản Google được liên kết hoặc đã phê duyệt." },
  googleNotConfigured: { en: "Google sign-in is not configured yet on this environment.", vi: "Google sign-in chưa được cấu hình." },
  signInWithEmail: { en: "Sign in with email", vi: "Đăng nhập bằng email" },
  ifYouSignedOut: { en: "If you signed out on this computer, the email and password fields will show again here.", vi: "Các trường đăng nhập sẽ hiển thị lại nếu bạn đã đăng xuất trên máy này." },
  passwordPlaceholder: { en: "Enter your password", vi: "Nhập mật khẩu của bạn" },
  hidePassword: { en: "Hide password", vi: "Ẩn mật khẩu" },
  showPassword: { en: "Show password", vi: "Hiện mật khẩu" },
  rememberLogin: { en: "Remember this login on this computer", vi: "Ghi nhớ đăng nhập trên máy tính này" },
  signingIn: { en: "Signing in...", vi: "Đang đăng nhập..." },
  logInWithEmailBtn: { en: "Log in with email", vi: "Đăng nhập bằng email" },
  accountSecurity: { en: "Account Security", vi: "Bảo mật Tài khoản" },
  firstLoginDetected: { en: "First login detected. Please change your password before continuing to use the portal.", vi: "Phát hiện lần đăng nhập đầu. Vui lòng đổi mật khẩu trước khi tiếp tục." },
  changePasswordAnytime: { en: "You can change your password here at any time.", vi: "Bạn có thể đổi mật khẩu ở đây bất kỳ lúc nào." },
  currentPassword: { en: "Current password", vi: "Mật khẩu hiện tại" },
  enterCurrentPassword: { en: "Enter current password", vi: "Nhập mật khẩu hiện tại" },
  newPassword: { en: "New password", vi: "Mật khẩu mới" },
  chooseNewPassword: { en: "Choose a new password", vi: "Chọn mật khẩu mới" },
  pleaseLoginBeforeChange: { en: "Please log in before changing your password.", vi: "Vui lòng đăng nhập trước khi đổi mật khẩu." },
  enterBothPasswords: { en: "Enter both your current password and a new password.", vi: "Nhập cả mật khẩu hiện tại và mật khẩu mới." },
  unableToChangePassword: { en: "Unable to change password.", vi: "Không thể đổi mật khẩu." },
  passwordChangedSuccess: { en: "Password changed successfully.", vi: "Đã đổi mật khẩu thành công." },
  myInformation: { en: "My Information", vi: "Thông tin của tôi" },
  submitEmailToLoad: { en: "Submit your email to load the active Cozoronian row.", vi: "Gửi email của bạn để tải về thông tin Khách hàng đang hoạt động." },
  userViewShort: { en: "Cozoronian", vi: "Khách hàng" },
  managerViewShort: { en: "Manager", vi: "Quản lý" },
  managerWorkspace: { en: "Manager Workspace", vi: "Không gian làm việc quản lý" },
  openManagerOverview: { en: "Open manager overview", vi: "Mở tổng quan quản lý" },
  openOwnersEmployees: { en: "Open Owners & employees", vi: "Mở mục Chủ sở hữu & Nhân viên" },
  openCleaningScheduleAssign: { en: "Open Cleaning schedule assigning", vi: "Mở mục phân công lịch vệ sinh" },
  confirmPassword: { en: "Confirm new password", vi: "Xác nhận mật khẩu mới" },
  passwordsDoNotMatch: { en: "Passwords do not match.", vi: "Mật khẩu không khớp." },
  passwordTooShort: { en: "Password must be at least 4 characters.", vi: "Mật khẩu phải có ít nhất 4 ký tự." },
  changingPassword: { en: "Changing password...", vi: "Đang đổi mật khẩu..." },
  personalMessages: { en: "Personal", vi: "Cá nhân" },
  roomGroup: { en: "Room", vi: "Phòng" },
  floorGroup: { en: "Floor", vi: "Tầng" },
  branchGroup: { en: "Branch", vi: "Cơ sở" },
  sendAnonymously: { en: "Send anonymously (Hide my identity)", vi: "Gửi ẩn danh (Ẩn danh tính)" },
  sendAsCozoro: { en: "Send as Cozoro (Hide my name)", vi: "Gửi dưới tên Cozoro (Ẩn tên tôi)" },
  saySomethingToNeighbors: { en: "Say something to your neighbors...", vi: "Nói gì đó với hàng xóm của bạn..." },
  publicGroupHistory: { en: "Public group message history", vi: "Lịch sử tin nhắn nhóm công khai" },
  residentMessages: { en: "Messages & Community", vi: "Tin nhắn & Cộng đồng" },
  messagesChatDesc: { en: "Communicate with Cozoro staff or connect with your neighbors in group chats.", vi: "Trao đổi với nhân viên Cozoro hoặc kết nối với hàng xóm trong các nhóm chat." },
  room: { en: "Phòng", vi: "Phòng" },
  floor: { en: "Tầng", vi: "Tầng" },
  booking: { en: "Booking", vi: "Đặt lịch" },
  message: { en: "Message", vi: "Tin nhắn" },
  account: { en: "Account", vi: "Tài khoản" },
  moreDetail: { en: "More detail", vi: "Chi tiết hơn" },
  memberLabel: { en: "Cozoronian Member", vi: "Thành viên Khách hàng" },
  coinPortfolio: { en: "Coin Portfolio", vi: "Danh mục Coin" },
  thisMonthEarned: { en: "This Month Earned", vi: "Kiếm được tháng này" },
  thisMonthUsed: { en: "This Month Used", vi: "Sử dụng tháng này" },
  lastMonthEarned: { en: "Last Month Earned", vi: "Tháng trước kiếm được" },
  lastMonthUsed: { en: "Last Month Used", vi: "Tháng trước sử dụng" },
  recentTransactions: { en: "Recent Transactions", vi: "Giao dịch gần đây" },
  noRecentTransactions: { en: "No recent transactions.", vi: "Chưa có giao dịch gần đây." },
  viewFullHistory: { en: "View Full History", vi: "Xem toàn bộ lịch sử" },
  satisfied: { en: "Satisfied", vi: "Hài lòng" },
  neutral: { en: "Neutral", vi: "Bình thường" },
  unsatisfied: { en: "Unsatisfied", vi: "Không hài lòng" },
  optionalComment: { en: "Optional comment", vi: "Bình luận (không bắt buộc)" },
  send: { en: "Send", vi: "Gửi" },
  cancel: { en: "Cancel", vi: "Hủy" },
  leaveFeedback: { en: "Leave Feedback", vi: "Để lại phản hồi" },
  maintenanceIssue: { en: "Maintenance Issue", vi: "Vấn đề bảo trì" },
  reportedIssueSystemMsg: { en: "[System] Reported maintenance issue", vi: "[Hệ thống] Đã báo cáo vấn đề bảo trì" },
  cozoroSupport: { en: "Cozoro Support", vi: "Hỗ trợ Cozoro" },
  community: { en: "Community", vi: "Cộng đồng" },
  soundOn: { en: "Sound On", vi: "Bật âm thanh" },
  soundOff: { en: "Sound Off", vi: "Tắt âm thanh" },
  report: { en: "Report", vi: "Báo cáo" },
  loadingMessages: { en: "Loading messages...", vi: "Đang tải tin nhắn..." },
  startChatDesc: { en: "No messages yet. Start the conversation here.", vi: "Chưa có tin nhắn. Hãy bắt đầu cuộc trò chuyện tại đây." },
  you: { en: "You", vi: "Bạn" },
  neighbor: { en: "Neighbor", vi: "Hàng xóm" },
  askAnything: { en: "Ask anything...", vi: "Hỏi bất cứ điều gì..." },
  saySomething: { en: "Say something...", vi: "Nói điều gì đó..." },
  anonymousOn: { en: "Anonymous On", vi: "Đang bật ẩn danh" },
  anonymousOff: { en: "Anonymous Off", vi: "Đang tắt ẩn danh" },
  maintenanceReport: { en: "Maintenance Report", vi: "Báo cáo bảo trì" },
  reportSubtext: { en: "Submit a ticket to earn 5000 coins.", vi: "Gửi phiếu yêu cầu để nhận 5000 coin." },
  location: { en: "Location", vi: "Vị trí" },
  selectLocation: { en: "Select location...", vi: "Chọn vị trí..." },
  myRoom: { en: "My Room", vi: "Phòng của tôi" },
  kitchen: { en: "Kitchen", vi: "Nhà bếp" },
  laundryArea: { en: "Laundry Area", vi: "Khu vực giặt sấy" },
  bathroom: { en: "Bathroom", vi: "Nhà vệ sinh" },
  otherLocation: { en: "Other...", vi: "Khác..." },
  specificLocationPlaceholder: { en: "e.g. Balcony 3rd floor...", vi: "vd: Ban công tầng 3..." },
  machineDevice: { en: "Device (Optional)", vi: "Thiết bị (Không bắt buộc)" },
  machinePlaceholder: { en: "e.g. Washer D7, AC...", vi: "vd: Máy giặt D7, Máy lạnh..." },
  issueDescription: { en: "Description", vi: "Mô tả vấn đề" },
  issuePlaceholder: { en: "What's wrong?", vi: "Có chuyện gì vậy?" },
  submitting: { en: "Submitting...", vi: "Đang gửi..." },
  submitReport: { en: "Submit Maintenance Ticket", vi: "Gửi phiếu bảo trì" },
  staff: { en: "Staff", vi: "Nhân viên" },
  staffView: { en: "Staff view", vi: "Giao diện nhân viên" },
  maintenance: { en: "Maintenance & Malfunctions", vi: "Báo trì & Sự cố" },
  reportNewIssue: { en: "Report in Messages", vi: "Báo cáo qua Tin nhắn" },
  noActiveTickets: { en: "No active maintenance tickets.", vi: "Không có phiếu bảo trì nào đang hoạt động." },
  cozoroLabel: { en: "Cozoro", vi: "Cozoro" },
  anonymous: { en: "Anonymous", vi: "Ẩn danh" },
  unableToLoadChat: { en: "Unable to load chat.", vi: "Không thể tải đoạn hội thoại." },
  unableToLoadGroupMessages: { en: "Unable to load group messages.", vi: "Không thể tải tin nhắn nhóm." },
  enterMessageFirst: { en: "Please enter a message first.", vi: "Vui lòng nhập tin nhắn trước." },
  unableToSendMessage: { en: "Unable to send your message.", vi: "Không thể gửi tin nhắn của bạn." },
  messageSent: { en: "Message sent.", vi: "Đã gửi tin nhắn." },
  fillRequiredFields: { en: "Please fill in location and issue description.", vi: "Vui lòng điền vị trí và mô tả sự cố." },
  unableToSubmitReport: { en: "Unable to submit report.", vi: "Không thể gửi báo cáo." },
  reportSuccess: { en: "Report submitted successfully! 5000 coins added to your account.", vi: "Gửi báo cáo thành công! 5000 coin đã được cộng vào tài khoản của bạn." },
  totalBookings: { en: "Total bookings", vi: "Tổng số lượt đặt" },
  upcoming: { en: "Upcoming", vi: "Sắp tới" },
  completed: { en: "Completed", vi: "Đã hoàn thành" },
  nextBooking: { en: "Next booking", vi: "Lượt đặt tiếp theo" },
  noUpcomingBooking: { en: "No upcoming booking", vi: "Không có lượt đặt sắp tới" },
  currentBalance: { en: "Current balance", vi: "Số dư hiện tại" },
  lifetimeCoins: { en: "Lifetime coins", vi: "Tổng coin tích lũy" },
  coinsAdded: { en: "Coins added", vi: "Coin đã cộng" },
  coinsUsed: { en: "Coins used", vi: "Coin đã dùng" },
  paymentCount: { en: "Payment count", vi: "Số lượt thanh toán" },
  totalPaid: { en: "Total paid", vi: "Tổng đã thanh toán" },
  averagePayment: { en: "Average payment", vi: "Thanh toán trung bình" },
  latestPayment: { en: "Latest payment", vi: "Thanh toán gần nhất" },
  noPaymentsYet: { en: "No payments yet", vi: "Chưa có thanh toán" },
  fineCount: { en: "Fine count", vi: "Số lượt phạt" },
  unpaidFines: { en: "Unpaid fines", vi: "Tiền phạt chưa đóng" },
  totalFineValue: { en: "Total fine value", vi: "Tổng giá trị phạt" },
  nearestDueDate: { en: "Nearest due date", vi: "Hạn đóng gần nhất" },
  noDueDate: { en: "No due date", vi: "Không có hạn đóng" },
  unassigned: { en: "Unassigned", vi: "Chưa phân bổ" },
  rooms: { en: "Rooms", vi: "Phòng" },
  branches: { en: "Branches", vi: "Chi nhánh" },
  floors: { en: "Floors", vi: "Tầng" },
  occupiedBeds: { en: "Occupied beds", vi: "Số giường đã có người" },
  clients: { en: "Clients", vi: "Khách hàng" },
  unableToLoadClients: { en: "Unable to load clients.", vi: "Không thể tải danh sách khách hàng." },
  clientDataRefreshed: { en: "Client data refreshed.", vi: "Dữ liệu khách hàng đã được làm mới." },
  clientListLoaded: { en: "Client list loaded.", vi: "Đã tải danh sách khách hàng." },
  unableToLoadWorkspace: { en: "Unable to load client workspace.", vi: "Không thể tải không gian làm việc của khách hàng." },
  loadedTabFor: { en: "Loaded {tab} for {name}.", vi: "Đã tải {tab} cho {name}." },
  unableToLoadTeam: { en: "Unable to load owners and employees.", vi: "Không thể tải danh sách chủ sở hữu và nhân viên." },
  failedControlAc: { en: "Failed to control AC", vi: "Điều khiển điều hòa thất bại" },
  networkErrorAc: { en: "Network error controlling AC", vi: "Lỗi mạng khi điều khiển điều hòa" },
  manualOverrideWarning: { en: "WARNING: Manual override for {id}. This will bypass resident booking schedules. Proceed?", vi: "CẢNH BÁO: Ghi đè thủ công cho {id}. Hành động này sẽ bỏ qua lịch đặt của cư dân. Tiếp tục?" },
  triggeredSuccess: { en: "{id} triggered successfully.", vi: "Kích hoạt {id} thành công." },
  failedToTrigger: { en: "Failed to trigger {type}", vi: "Kích hoạt {type} thất bại" },
  networkErrorTrigger: { en: "Network error triggering {type}", vi: "Lỗi mạng khi kích hoạt {type}" },
  requestFailed: { en: "Request failed.", vi: "Yêu cầu thất bại." },
  unableToLoadFeedbacks: { en: "Unable to load feedbacks.", vi: "Không thể tải phản hồi." },
  unableToUploadFineImage: { en: "Unable to upload fine image.", vi: "Không thể tải ảnh vi phạm lên." },
  fineImageUploaded: { en: "Fine image uploaded.", vi: "Đã tải ảnh vi phạm lên." },
  cozoroSide: { en: "Cozoro Side", vi: "Dành cho Cozoro" },
  staffLoginRequired: { en: "Sign in with a Cozoro, manager, or owner account to search clients, send messages, create fine tickets, add coin entries, and review client statistics.", vi: "Đăng nhập bằng tài khoản Cozoro, quản lý hoặc chủ sở hữu để tìm kiếm khách hàng, gửi tin nhắn, tạo phiếu phạt, thêm coin và xem thống kê khách hàng." },
  managementWorkspace: { en: "Management Workspace", vi: "Không gian quản lý" },
  managementWorkspaceDesc: { en: "Search clients, edit their profile, send messages, create fine tickets and coin entries, then open laundry, coins, payments, or fines from latest to oldest.", vi: "Tìm kiếm khách hàng, chỉnh sửa hồ sơ, gửi tin nhắn, tạo phiếu phạt và mục nhập coin, sau đó xem lịch sử giặt ủi, coin, thanh toán hoặc tiền phạt từ mới nhất đến cũ nhất." },
  refreshData: { en: "Refresh data", vi: "Làm mới dữ liệu" },
  browseList: { en: "1. Browse List", vi: "1. Xem danh sách" },
  clientDetailsTab: { en: "2. Client Details", vi: "2. Chi tiết khách hàng" },
  branchD2: { en: "Branch D2", vi: "Chi nhánh D2" },
  branchD7: { en: "Branch D7", vi: "Chi nhánh D7" },
  newGroupMessage: { en: "+ New Group Message", vi: "+ Tin nhắn nhóm mới" },
  diagram: { en: "Diagram", vi: "Sơ đồ" },
  table: { en: "Table", vi: "Bảng" },
  bedsLabel: { en: "beds", vi: "giường" },
  bedLabel: { en: "Bed", vi: "Giường" },
  emptyLabel: { en: "Empty", vi: "Trống" },
  tableHeaderName: { en: "Name", vi: "Tên" },
  tableHeaderContract: { en: "Contract", vi: "Hợp đồng" },
  tableHeaderPhone: { en: "Phone", vi: "Số điện thoại" },
  tableHeaderStatus: { en: "Status", vi: "Trạng thái" },
  activeStatus: { en: "Active", vi: "Đang hoạt động" },
  selectedClient: { en: "Selected Client", vi: "Khách hàng đang chọn" },
  chooseClientPrompt: { en: "Choose a client from the list.", vi: "Xem danh sách để chọn khách hàng." },
  hideDetails: { en: "Hide details", vi: "Ẩn chi tiết" },
  showDetails: { en: "Show details", vi: "Hiện chi tiết" },
  editProfile: { en: "Edit profile", vi: "Sửa hồ sơ" },
  messageRoom: { en: "Message Room", vi: "Nhắn tin cho phòng" },
  messageBranch: { en: "Message Branch", vi: "Nhắn tin cho chi nhánh" },
  callClient: { en: "Call client", vi: "Gọi cho Khách hàng" },
  textClient: { en: "Text client", vi: "Nhắn tin cho Khách hàng" },
  emailClient: { en: "Email client", vi: "Email cho Khách hàng" },
  openChat: { en: "Open chat", vi: "Mở chat" },
  newFineTicket: { en: "New fine ticket", vi: "Tạo phiếu phạt" },
  newCoinsEntry: { en: "New coins entry", vi: "Tạo mục nhập coin" },
  newPaymentReceipt: { en: "New payment receipt", vi: "Tạo biên lai thanh toán" },
  closeLabel: { en: "Close", vi: "Đóng" },
  clientChatTitle: { en: "Client Chat", vi: "Trò chuyện với Khách hàng" },
  createPaymentReceipt: { en: "Create Payment Receipt", vi: "Tạo biên lai thanh toán" },
  createFineTicket: { en: "Create Fine Ticket", vi: "Tạo phiếu phạt" },
  createCoinsEntry: { en: "Create Coins Entry", vi: "Tạo mục nhập coin" },
  startCall: { en: "Start call", vi: "Bắt đầu gọi" },
  clientProfileUpdated: { en: "Client profile updated.", vi: "Đã cập nhật hồ sơ khách hàng." },
  submitProfileChanges: { en: "Submit profile changes", vi: "Gửi thay đổi hồ sơ" },
  cancelEdit: { en: "Cancel edit", vi: "Hủy chỉnh sửa" },
  categoryCoinsCurrent: { en: "current", vi: "hiện tại" },
  categoryCoinsLifetime: { en: "lifetime", vi: "tích lũy" },
  clientActions: { en: "Client Actions", vi: "Hành động khách hàng" },
  chooseActionPrompt: { en: "Choose an action first, then complete it in the popup form.", vi: "Chọn một hành động trước, sau đó hoàn tất trong mẫu hiện lên." },
  openEmail: { en: "Open email", vi: "Mở email" },
  conversationWith: { en: "Conversation with {name}", vi: "Trò chuyện với {name}" },
  refreshChat: { en: "Refresh chat", vi: "Làm mới chat" },
  loadingChat: { en: "Loading chat...", vi: "Đang tải đoạn chat..." },
  noChatMessagesStarted: { en: "No chat messages yet. Start the conversation below.", vi: "Chưa có tin nhắn. Hãy bắt đầu trò chuyện ở dưới." },
  replyPlaceholder: { en: "Write a reply to this client...", vi: "Viết phản hồi cho khách hàng..." },
  sendReply: { en: "Send reply", vi: "Gửi phản hồi" },
  rentCalculation: { en: "Rent Calculation", vi: "Tính tiền phòng" },
  simpleReceipt: { en: "Simple Receipt", vi: "Biên lai đơn giản" },
  targetMonth: { en: "Target Month", vi: "Tháng tính tiền" },
  managerDiscountVnd: { en: "Manager Discount (VND)", vi: "Giảm trừ quản lý (VND)" },
  calculating: { en: "Calculating...", vi: "Đang tính toán..." },
  calculateRentBreakdown: { en: "Calculate Rent Breakdown", vi: "Tính chi tiết tiền phòng" },
  breakdownFor: { en: "Breakdown for {month}", vi: "Chi tiết cho {month}" },
  baseRent: { en: "Base Rent", vi: "Tiền phòng cơ bản" },
  tenureSurcharge: { en: "Tenure Surcharge", vi: "Phụ phí thâm niên" },
  professionalDiscount: { en: "Professional Discount", vi: "Ưu đãi chuyên gia" },
  planDiscount: { en: "Plan Discount", vi: "Ưu đãi theo gói" },
  managerDiscount: { en: "Manager Discount", vi: "Giảm trừ quản lý" },
  parkingFee: { en: "Parking Fee", vi: "Phí gửi xe" },
  laundryFeeLabel: { en: "Laundry Fee ({count} paid uses)", vi: "Phí giặt sấy ({count} lượt có phí)" },
  unpaidFinesLabel: { en: "Unpaid Fines", vi: "Tiền phạt chưa đóng" },
  subtotal: { en: "Subtotal", vi: "Tạm tính" },
  coinUsageLabel: { en: "Coin Usage ({count} coins)", vi: "Sử dụng Coin ({count} coin)" },
  totalDue: { en: "Total Due", vi: "Tổng tiền cần đóng" },
  payerName: { en: "Payer Name", vi: "Tên người đóng" },
  confirmSendReceipt: { en: "Confirm & Send Receipt", vi: "Xác nhận & Gửi biên lai" },
  paymentRecordedSuccess: { en: "Payment recorded and receipt sent via Gmail!", vi: "Đã ghi nhận thanh toán và gửi biên lai qua Gmail!" },
  amountLabel: { en: "Amount", vi: "Số tiền" },
  purposeLabel: { en: "Purpose", vi: "Mục đích" },
  detailsLabel: { en: "Details", vi: "Chi tiết" },
  dormBranch: { en: "Dorm Branch", vi: "Chi nhánh Dorm" },
  receiverEmail: { en: "Receiver Email address", vi: "Địa chỉ email người nhận" },
  discountAmount: { en: "Discount amount", vi: "Số tiền ưu đãi" },
  discountCondition: { en: "Discount condition", vi: "Điều kiện ưu đãi" },
  addLabel: { en: "Add", vi: "Thêm" },
  otherPurposePlaceholder: { en: "Other purpose...", vi: "Mục đích khác..." },
  paymentReceiptCreated: { en: "Payment receipt created.", vi: "Đã tạo biên nhận thanh toán." },
  fineTicketCreated: { en: "Fine ticket created.", vi: "Đã tạo phiếu phạt." },
  addingCoins: { en: "Adding coins", vi: "Cộng coin" },
  usingCoins: { en: "Using coins", vi: "Sử dụng coin" },
  searchCreateEvent: { en: "Search or create event", vi: "Tìm hoặc tạo sự kiện" },
  searchEventsPlaceholder: { en: "Search available events or type a new one", vi: "Tìm sự kiện có sẵn hoặc nhập mới" },
  previousEntriesHeader: { en: "Available options and previous entries", vi: "Tùy chọn có sẵn và các mục cũ" },
  noMatchFoundCreate: { en: "No match found. You can create a new event by typing it above.", vi: "Không tìm thấy kết quả. Bạn có thể tạo sự kiện mới bằng cách nhập vào trên." },
  coinsAmountPlaceholder: { en: "Coins amount", vi: "Số lượng coin" },
  coinsEntryCreated: { en: "Coins entry created.", vi: "Đã tạo mục nhập coin." },
  clientStatistics: { en: "Client Statistics", vi: "Thống kê Khách hàng" },
  clientStatsDesc: { en: "Open laundry, coins, payments, or fines on demand. Each tab starts with a summary, and raw entries only appear when requested.", vi: "Mở lịch sử giặt ủi, coin, thanh toán hoặc tiền phạt. Mỗi tab bắt đầu bằng tóm tắt và chỉ hiện chi tiết khi được yêu cầu." },
  statsSelectPrompt: { en: "Select a client and press one of the statistic buttons.", vi: "Chọn một khách hàng và nhấn một trong các nút thống kê." },
  laundryPackingDesc: { en: "Laundry entries are packed into a scroll panel so the manager page stays shorter.", vi: "Lịch sử giặt ủi được đóng gói trong khung cuộn để trang quản lý gọn hơn." },
  compactPanelDesc: { en: "Showing a compact entries panel with its own scroll area.", vi: "Hiển thị khung chi tiết thu gọn với vùng cuộn riêng." },
  whenLabel: { en: "When", vi: "Thời gian" },
  detailLabel: { en: "Detail", vi: "Chi tiết" },
  saveLabel: { en: "Save", vi: "Lưu" },
  ownersEmployees: { en: "Owners & employees", vi: "Chủ sở hữu & Nhân viên" },
  ownersEmployeesDesc: { en: "Store and review Cozoro-side accounts with manager, owner, or app admin status.", vi: "Lưu trữ và xem xét các tài khoản phía Cozoro với quyền quản lý, chủ sở hữu hoặc quản trị viên ứng dụng." },
  refreshAccounts: { en: "Refresh accounts", vi: "Làm mới tài khoản" },
  languagePreference: { en: "Language Preference", vi: "Cài đặt ngôn ngữ" },
  chooseDisplayLanguage: { en: "Choose the display language for the management portal.", vi: "Chọn ngôn ngữ hiển thị cho cổng quản lý." },
  yourDisplayName: { en: "Your Display Name", vi: "Tên hiển thị của bạn" },
  displayNameDesc: { en: "This name appears on payment receipts. Your email cannot be changed.", vi: "Tên này hiển thị trên biên lai thanh toán. Email không thể thay đổi." },
  displayNamesSaved: { en: "Display name saved.", vi: "Đã lưu tên hiển thị." },
  createUpdateAccess: { en: "Create or update account access", vi: "Tạo hoặc cập nhật quyền truy cập tài khoản" },
  promoteManagerPrompt: { en: "App admin can add managers and owners. A selected client can also be promoted to manager.", vi: "Quản trị viên có thể thêm quản lý và chủ sở hữu. Một khách hàng được chọn cũng có thể được thăng cấp lên quản lý." },
  makeClientManager: { en: "Make selected client a manager", vi: "Đặt khách hàng đang chọn làm quản lý" },
  selectedClientEmail: { en: "Selected client email: {email}", vi: "Email khách hàng đang chọn: {email}" },
  saveAccount: { en: "Save account", vi: "Lưu tài khoản" },
  accountAccessUpdated: { en: "Account access updated. New accounts will be asked to change password on first login.", vi: "Đã cập nhật quyền truy cập. Tài khoản mới sẽ được yêu cầu đổi mật khẩu khi đăng nhập lần đầu." },
  managersViewOnly: { en: "Managers can view the owners and employees directory here, but only owners or the app admin can change it.", vi: "Quản lý có thể xem danh sách nhân viên ở đây, nhưng chỉ chủ sở hữu hoặc quản trị viên mới có thể thay đổi." },
  roleLabel: { en: "Role", vi: "Vai trò" },
  addedByLabel: { en: "Added by", vi: "Thêm bởi" },
  removeLabel: { en: "Remove", vi: "Xóa" },
  viewOnly: { en: "View only", vi: "Chỉ xem" },
  noAccountsAdded: { en: "No owners or employees have been added yet.", vi: "Chưa có chủ sở hữu hoặc nhân viên nào được thêm." },
  residentFeedbacks: { en: "Resident Feedbacks", vi: "Phản hồi Cư dân" },
  reviewNotesDesc: { en: "Review notes submitted by residents via the portal.", vi: "Xem xét các ghi chú được cư dân gửi qua cổng thông tin." },
  contractExpiredWarning: { en: "Your contract has expired!", vi: "Hợp đồng của bạn đã hết hạn!" },
  contractExpiredSub: { en: "All portal services are currently restricted. Please use the extension button below to continue living at Cozoro Home and regain access.", vi: "Tất cả các dịch vụ trên cổng thông tin đang bị hạn chế. Vui lòng nhấn nút gia hạn bên dưới để tiếp tục ở tại Cozoro Home và khôi phục quyền truy cập." },
  removeResident: { en: "Remove Resident", vi: "Xóa Cư dân" },
  confirmRemoveResident: { en: "Are you sure you want to remove this resident from the list? Their status will be set to -1.", vi: "Bạn có chắc chắn muốn xóa cư dân này khỏi danh sách? Trạng thái của họ sẽ được đặt thành -1." },
  residentRemoved: { en: "Resident removed from active list.", vi: "Đã xóa cư dân khỏi danh sách hoạt động." },
  extensionSubmitted: { en: "Extension Submitted!", vi: "Đã gửi gia hạn!" },
  processingWait: { en: "Success! Our system is generating your new contract email now.", vi: "Thành công! Hệ thống đang khởi tạo email hợp đồng mới của bạn." },
  checkEmailFifteenSeconds: { en: "Your contract is being processed. Please wait about 15 seconds for your account to reactivate automatically. An email will also be sent to your inbox.", vi: "Hợp đồng của bạn đang được xử lý. Vui lòng đợi khoảng 15 giây để tài khoản tự động kích hoạt lại. Một bản sao cũng sẽ được gửi đến email của bạn." },
  gotIt: { en: "Got it!", vi: "Đã hiểu!" },

  // Cleaning schedule
  cleaningScheduleTitle: { en: "Cleaning Schedule", vi: "Lịch vệ sinh" },
  cleaningScheduleDesc: { en: "Click a date to mark yourself unavailable or assign yourself to a cleaning task that fits your branch and floor.", vi: "Nhấn vào ngày để đánh dấu không rảnh hoặc đăng ký nhận lịch trực vệ sinh phù hợp với chi nhánh và tầng của bạn." },
  loadCleaningSchedule: { en: "Load cleaning schedule", vi: "Tải lịch vệ sinh" },
  refreshSchedule: { en: "Refresh schedule", vi: "Làm mới lịch" },
  refreshingSchedule: { en: "Refreshing...", vi: "Đang làm mới..." },
  cleaningProfileTitle: { en: "My Cleaning Profile", vi: "Hồ sơ vệ sinh của tôi" },
  cleaningOptOutTitle: { en: "Cleaning Opt-out", vi: "Không tham gia vệ sinh" },
  cleaningOptOutDesc: { en: "Pay 100,000 VND or 150,000 coins to be exempt from all cleaning assignments this month.", vi: "Trả 100.000 VND hoặc 150.000 coin để được miễn tất cả lịch trực vệ sinh trong tháng này." },
  cleaningOptedOut: { en: "You have opted out this month (paid via {method}). You will not be assigned to any cleaning tasks.", vi: "Bạn đã chọn không tham gia tháng này (thanh toán qua {method}). Bạn sẽ không được phân công vào lịch trực vệ sinh nào." },
  contractCleaningOptedOut: { en: "You are exempt from cleaning assignments for your current contract. Cleaning fee: {amount}/month.", vi: "Bạn được miễn các lịch trực vệ sinh cho hợp đồng hiện tại. Phí vệ sinh: {amount}/tháng." },
  cleaningFeeActive: { en: "Cleaning fee active", vi: "Đang áp dụng phí vệ sinh" },
  cancelOptOut: { en: "Cancel opt-out", vi: "Hủy không tham gia" },
  optOutThisMonth: { en: "Opt out this month", vi: "Không tham gia tháng này" },
  optOutModalTitle: { en: "Opt out of cleaning", vi: "Không tham gia vệ sinh" },
  optOutModalDesc: { en: "You will be exempt from all cleaning assignments this month. A fee will be charged.", vi: "Bạn sẽ được miễn tất cả lịch trực vệ sinh trong tháng này. Một khoản phí sẽ được thu." },
  pay100kVnd: { en: "Pay 100,000 VND", vi: "Trả 100.000 VND" },
  pay100kVndDesc: { en: "A fine will be added to your account.", vi: "Một khoản phạt sẽ được thêm vào tài khoản của bạn." },
  pay150kCoins: { en: "Pay 150,000 Coins", vi: "Trả 150.000 Coin" },
  pay150kCoinsDesc: { en: "Deducted from your coin balance immediately.", vi: "Trừ ngay từ số dư coin của bạn." },
  confirmOptOut: { en: "Confirm Opt Out", vi: "Xác nhận không tham gia" },
  processingOptOut: { en: "Processing...", vi: "Đang xử lý..." },
  upcomingOpenSlots: { en: "Upcoming open slots — available to self-assign", vi: "Lịch trống sắp tới — có thể tự đăng ký" },
  upcomingOpenSlotsHelp: { en: "These are unclaimed slots that match your branch and floor. Click a date to open it on the calendar and assign yourself.", vi: "Đây là các lịch chưa có người nhận phù hợp với chi nhánh và tầng của bạn. Nhấn vào ngày để mở trên lịch và tự đăng ký." },
  markAwayHelp: { en: "Mark Away lets you block multiple days at once as unavailable — useful if you are traveling or on leave.", vi: "Mark Away cho phép bạn đánh dấu nhiều ngày liên tiếp là không rảnh — hữu ích khi bạn đi xa hoặc nghỉ phép." },
  optOutHelp: { en: "Opt Out pays a one-time fee (100,000 VND or 150,000 coins) to skip ALL cleaning assignments for this month entirely.", vi: "Opt Out trả một lần (100.000 VND hoặc 150.000 coin) để bỏ qua toàn bộ lịch trực vệ sinh trong tháng này." },
  cleaningCalendarTitle: { en: "Cleaning Calendar", vi: "Lịch vệ sinh" },
  cleaningCalendarDesc: { en: "Select a date to set availability or claim a task yourself.", vi: "Chọn ngày để đặt trạng thái rảnh/bận hoặc tự nhận lịch trực." },
  prevMonth: { en: "Prev", vi: "Tháng trước" },
  nextMonth: { en: "Next", vi: "Tháng sau" },
  todayBtn: { en: "Today", vi: "Hôm nay" },
  markAwayBtn: { en: "Mark Away", vi: "Đánh dấu vắng" },
  cancelAwayBtn: { en: "Cancel Away", vi: "Hủy đánh dấu vắng" },
  datesSelected: { en: "{n} date{s} selected", vi: "{n} ngày đã chọn" },
  savingAway: { en: "Saving...", vi: "Đang lưu..." },
  taskActionsHeader: { en: "Task Actions", vi: "Thao tác lịch trực" },
  coinsBonusBadge: { en: "+20% Coins Bonus", vi: "+20% Bonus Coin" },
  noCleaningProfile: { en: "Your cleaning profile hasn't been set up yet. Contact your manager to be added to the system.", vi: "Hồ sơ vệ sinh của bạn chưa được thiết lập. Liên hệ quản lý để được thêm vào hệ thống." },
  takeOver: { en: "Take Over", vi: "Nhận thay" },
  takeOverDesc: { en: "assigned person hasn't completed it yet", vi: "người được giao chưa hoàn thành" },
  alreadyAssigned: { en: "Already assigned", vi: "Đã có người nhận" },
  assignMyself: { en: "Assign Myself", vi: "Tự đăng ký" },
  selfAssignedLabel: { en: "Self-assigned", vi: "Tự đăng ký" },
  freeReleaseLabel: { en: "Free release", vi: "Hủy miễn phí" },
  autoScheduledLabel: { en: "Auto-scheduled", vi: "Hệ thống phân công" },
  assignedByManagerLabel: { en: "Assigned by manager", vi: "Quản lý phân công" },
  notApproved: { en: "Not approved", vi: "Không được duyệt" },
  approvedCoinsAdded: { en: "Approved — +{coins} coins added to your account", vi: "Đã duyệt — +{coins} coin đã cộng vào tài khoản" },
  removeMyself: { en: "Remove Myself ({penalty})", vi: "Hủy đăng ký ({penalty})" },
  availabilityHeader: { en: "Availability", vi: "Trạng thái rảnh/bận" },
  markUnavailable: { en: "Mark Unavailable", vi: "Đánh dấu không rảnh" },
  markUnavailableDesc: { en: "You won't be assigned on this day.", vi: "Bạn sẽ không được phân công vào ngày này." },
  selectedDateTitle: { en: "Selected Date", vi: "Ngày đã chọn" },
  currentStatusLabel: { en: "Current status", vi: "Trạng thái hiện tại" },
  noAvailabilityPref: { en: "No availability preference saved", vi: "Chưa lưu trạng thái rảnh/bận" },
  noteLabel: { en: "Note", vi: "Ghi chú" },
  optionalNotePlaceholder: { en: "Optional note for this date", vi: "Ghi chú tùy chọn cho ngày này" },
  markUnavailableBtn: { en: "Mark unavailable", vi: "Đánh dấu không rảnh" },
  markAvailableBtn: { en: "Mark available", vi: "Đánh dấu rảnh" },
  assignMyselfOnDate: { en: "Assign myself on this date", vi: "Tự đăng ký ngày này" },
  onlyTodayOrFuture: { en: "You can only assign yourself to today or future dates.", vi: "Bạn chỉ có thể tự đăng ký cho hôm nay hoặc các ngày trong tương lai." },
  suggestedNearbyDates: { en: "Suggested nearby open dates", vi: "Ngày trống gần đây được gợi ý" },
  trashFollowsFloor: { en: "Your D7 trash task follows floor {floor} automatically.", vi: "Lịch đổ rác D7 của bạn tự động theo tầng {floor}." },
  readyToSubmit: { en: "Ready to submit", vi: "Sẵn sàng gửi" },
  pendingAssignNote: { en: "Nothing will be changed until you confirm and submit this task.", vi: "Không có gì thay đổi cho đến khi bạn xác nhận và gửi lịch trực này." },
  cannotSelfAssign: { en: "This date cannot be self-assigned.", vi: "Ngày này không thể tự đăng ký." },
  confirmAndSubmit: { en: "Confirm and submit", vi: "Xác nhận và gửi" },
  tasksOnDate: { en: "Tasks on this date", vi: "Lịch trực ngày này" },
  noTasksOnDate: { en: "No tasks assigned on this date yet.", vi: "Chưa có lịch trực nào vào ngày này." },
  statusLabel: { en: "Status", vi: "Trạng thái" },
  rewardLabel: { en: "Reward", vi: "Thưởng" },
  assignerLabel: { en: "Assigner", vi: "Người phân công" },
  floorTaskLabel: { en: "Floor", vi: "Tầng" },
  upcomingTasksTitle: { en: "Upcoming Tasks", vi: "Lịch trực sắp tới" },
  reschedulePolicyNote: { en: "Reschedule policy: 5+ days notice has no fine, 1–4 days notice has a 50% fine, same-day notice has a 75% fine, and missing the work is a full fine. Late completion: You may mark a task done up to 10 hours after the deadline and still earn 50% of the normal coin reward. After 10 hours the task is marked missed and a fine is issued automatically.", vi: "Chính sách đổi lịch: Báo trước 5+ ngày không bị phạt, 1–4 ngày phạt 50%, cùng ngày phạt 75%, bỏ lịch bị phạt toàn bộ. Nộp muộn: Bạn có thể đánh dấu xong trong vòng 10 giờ sau deadline và vẫn nhận 50% coin. Sau 10 giờ lịch bị đánh dấu missed và tự động phạt." },
  noUpcomingTasks: { en: "No upcoming tasks.", vi: "Không có lịch trực sắp tới." },
  completionWindow: { en: "Completion window", vi: "Khung giờ hoàn thành" },
  completionNotePlaceholder: { en: "Optional completion note", vi: "Ghi chú hoàn thành (không bắt buộc)" },
  markDoneBtn: { en: "Mark done", vi: "Đánh dấu xong" },
  markDoneLateBtn: { en: "Mark done (late — 50% coins)", vi: "Đánh dấu xong (muộn — 50% coin)" },
  lateSubmissionWarning: { en: "⚠ Late submission. You will earn {earned} coins (50%) instead of {full}. Deadline: {time}.", vi: "⚠ Nộp muộn. Bạn sẽ nhận {earned} coin (50%) thay vì {full}. Hạn cuối: {time}." },
  deadlinePassed: { en: "Deadline passed. You had until {time} to submit late.", vi: "Đã quá hạn. Bạn có thể nộp muộn đến {time}." },
  removeMyselfBtn: { en: "Remove myself ({penalty})", vi: "Hủy đăng ký ({penalty})" },
  allRemovalsUsed: { en: "You have used all {limit} removals for this month.", vi: "Bạn đã dùng hết {limit} lượt hủy trong tháng này." },
  willBeReassigned: { en: "You will be automatically reassigned to another date. ({used}/{limit} removals used this month)", vi: "Bạn sẽ được phân công lại sang ngày khác. ({used}/{limit} lượt hủy đã dùng trong tháng)." },
  willBeReassignedFree: { en: "You will be reassigned to another date. This will not count against your monthly removal limit.", vi: "Bạn sẽ được phân công lại sang ngày khác. Điều này sẽ không tính vào giới hạn hủy hàng tháng." },
  auditNoteLabel: { en: "Audit note", vi: "Ghi chú kiểm tra" },
  yourNoteLabel: { en: "Your note", vi: "Ghi chú của bạn" },
  pastTasksTitle: { en: "Past Tasks", vi: "Lịch trực đã qua" },
  monthFilterLabel: { en: "Month", vi: "Tháng" },
  yearFilterLabel: { en: "Year", vi: "Năm" },
  allMonths: { en: "All months", vi: "Tất cả tháng" },
  allYears: { en: "All years", vi: "Tất cả năm" },
  noPastTasks: { en: "No past tasks yet.", vi: "Chưa có lịch trực nào." },
  showFiveMore: { en: "Show 5 more", vi: "Xem thêm 5" },
  openSlotCalLabel: { en: "Open", vi: "Trống" },
  takenCalLabel: { en: "Taken", vi: "Bận" },
  offCalLabel: { en: "Off", vi: "Vắng" },
  awayCalLabel: { en: "Away", vi: "Vắng" },
  nextCleaningDueNow: { en: "Due now. Late submissions stay open until {deadline} and earn 50% coins.", vi: "Đã đến hạn. Có thể nộp muộn đến {deadline} và nhận 50% coin." },
  nextCleaningCanDone: { en: "You can mark this done during {window}.", vi: "Bạn có thể đánh dấu xong trong {window}." },
  nextCleaningOpensSoon: { en: "Mark done opens during {window}.", vi: "Có thể đánh dấu xong trong {window}." },
  markDoneCardBtn: { en: "Mark done", vi: "Đánh dấu xong" },
  markDoneLateCardBtn: { en: "Mark done (late - 50% coins)", vi: "Đánh dấu xong (muộn - 50% coin)" },
  trashFloorNote: { en: "Floor {floor}", vi: "Tầng {floor}" },
  atMonthlyLimitNote: { en: "You have used all {limit} removals for this month.", vi: "Bạn đã dùng hết {limit} lượt hủy trong tháng này." },
};

const PortalLanguageContext = createContext<PortalLanguageContextValue | null>(null);

export function PortalLanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<PortalLanguage>("en");

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    const saved = window.localStorage.getItem(PORTAL_LANGUAGE_STORAGE_KEY);
    if (saved === "en" || saved === "vi") {
      setLanguageState(saved);
    }
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    window.localStorage.setItem(PORTAL_LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language === "vi" ? "vi" : "en";
  }, [language]);

  const value = useMemo<PortalLanguageContextValue>(
    () => ({
      language,
      setLanguage: (nextLanguage) => setLanguageState(nextLanguage),
      t: (key, fallback) => translations[key]?.[language] ?? fallback ?? key
    }),
    [language]
  );

  return <PortalLanguageContext.Provider value={value}>{children}</PortalLanguageContext.Provider>;
}

export function usePortalLanguage() {
  const context = useContext(PortalLanguageContext);
  if (!context) {
    throw new Error("usePortalLanguage must be used inside PortalLanguageProvider");
  }

  return context;
}
