tunnel: ace69517-369e-44a3-9f00-3304bf2153df
credentials-file: C:\Users\User\.cloudflared\ace69517-369e-44a3-9f00-3304bf2153df.json

ingress:
  - hostname: app.cozorohome.com
    service: http://localhost:3000
  - hostname: chatbot.cozorohome.com
    service: http://127.0.0.1:4111
  - hostname: shortterm.cozorohome.com
    service: http://127.0.0.1:4115
  - service: http_status:404
