tunnel: c9b9a2cf-b529-42ff-acf8-7d68ddf6d930
credentials-file: C:\Users\User\.cloudflared\c9b9a2cf-b529-42ff-acf8-7d68ddf6d930.json

ingress:
  - hostname: shortterm.cozorohome.com
    service: http://127.0.0.1:4115
  - service: http_status:404
